packages:
  - "fe"

engineStrict: true
savePrefix: ""
resolutionMode: time-based
minimumReleaseAge: 1440
blockExoticSubdeps: true
strictDepBuilds: true

overrides:
  sharp: 0.34.4

allowBuilds:
  sharp: false
  unrs-resolver: false
